name: Release workflow

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install packages
      run: sudo apt install libsdl2-dev libasound-dev libvncserver-dev openjade docbook docbook-dsssl

    - name: create sources tarball
      run: tar czvf bochs.tar.gz --exclude=.git bochs

    - name: build linux binaries
      run: cd bochs && ./build/redhat/make-rpm | tee ../build.log

    - name: Upload release sources tarball
      uses: actions/upload-artifact@v4
      with:
        name: bochs.tar.gz
        path: bochs.tar.gz

    - name: Upload release linux RPM package
      uses: actions/upload-artifact@v4
      with:
        name: bochs linux RPM
        path: bochs/bochs-*.rpm
